FROM node:18.12.1 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm config rm proxy
RUN npm config rm https-proxy
# RUN npm config set fetch-retry-mintimeout 20000
# RUN npm config set fetch-retry-maxtimeout 120000
RUN chown -R node /app/node_modules
RUN npm install

COPY ./ /app/
ARG configuration=production
RUN npm run build -- --output-path=./dist/out --configuration $configuration

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.15
#Copy ci-dashboard-dist
COPY --from=build-stage /app/dist/out/ /usr/share/nginx/html
#Copy default nginx configuration
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf