version: "3"
services:
  nginx:
      image: nginx
      container_name: 'nginx'
      depends_on:
        - frontend
        - backend
      links:
        - frontend
        - backend
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "8080:80"
  frontend:
    build:
      context: ./frontend
    container_name: "frontend"
    # volumes:
    #   - shared:/app/dist
  backend:
    build:
      context: ./backend
    container_name: "backend"
    ports:
      - "8081:8081"